// <auto-generated />
namespace MediaStoreApi.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _initial_added_media_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_initial_added_media_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201706201300084__initial_added_media_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
